### ISSUE TITLE
use mono t4 in a vsix solution

### ISSUE THREAD

**Issue by kccarter76** [mono/t4#84] opened 2020-07-28 16:53 UTC
since you replicate the Microsoft.VisualStudio.TextTemplating namespace in mono t4. how would I consume this in a vsix solution?, the interfaces are defined in two locations.

yes I am aware of the Text Templating service in VS but, I have found that Microsoft's implementation is to rigid and is lacking the feature set needed to fulfill my requirements.  I will need to support full t4 script debugging and support the ability to load netstandard libraries.

**Comment by kccarter76** [comment] 2020-07-28 16:56
off the top of my head, mono t4 would need to change the namespace so it can build in a vsix solution. however, if there is a way to suppress the interfaces defined in the vhost, I would take that option.

**Comment by mhutch** [comment] 2020-11-30 20:48
This is by design, as this library was originally intended as a redistributable drop-in replacement for Microsoft.VisualStudio.TextTemplating.dll. Now that it's evolved beyond the original, I think it would be reasonable to change the namespace and modernize the API: https://github.com/mono/t4/issues/16. This would of course require a major version bump for SemVer.

However, this could potentially also break existing templates, as they could depend on the host interfaces and namespaces. It's a bit of an edge case but I don't like making breaking changes without having a migration story e.g. an optional shim library that hosts could choose to reference in order to allow templates that use the old API to continue to work.

**Comment by mhutch** [comment] 2020-12-03 16:45
Closing this in favor of #16 

In the mean time you should be able to use this in a vsix using [extern aliases](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias).

**Closed by mhutch** 2020-12-03 16:45 UTC
